import Head from "next/head";
import BackToHome from "../../components/BackToHome";
import SpeciesList from "../../components/SpeciesList";


const Planets = () => {
    return (
        <>
        <Head>
            <title>Planets</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <BackToHome />
        <div>
            <h1>Planets</h1>
            <SpeciesList />
        </div>
        </>
    );
};

export default Planets;
