import Head from "next/head";
import { useState } from "react";
import DataList from "../../components/DataList";
import Footer from "../../components/Footer";

const People: React.FC = () => {
  const [url, setUrl] = useState<string>("https://swapi.dev/api/people/");
  const getId = (url: string) => {
    const id = url.split("/")[5];
    return id;
  };
  const getImage = (id: string, name: string) => {
    const image = `https://starwars-visualguide.com/assets/img/characters/${id}.jpg`;
    return image;
  };
  return (
    <>
      <Head>
        <title>People</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>People</h1>
        <DataList
          url={url}
          getId={getId}
          getImage={getImage}
          category="people"
          setUrl={setUrl}
        />
      </div>
      <Footer />
    </>
  );
};

export default People;
