import Head from "next/head";
import BackToHome from "../../components/BackToHome";
import StarshipsList from "../../components/StarshipsList";


const Starships = () => {
    return (
        <>
        <Head>
            <title>Starships</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <BackToHome />
        <div>
            <h1>Starships</h1>
            <StarshipsList />
        </div>
        </>
    );
};

export default Starships;
