import Head from "next/head";
import BackToHome from "../../components/BackToHome";
import VehiclesList from "../../components/VehiclesList";


const Vehicles = () => {
    return (
        <>
        <Head>
            <title>Vehicles</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <BackToHome />
        <div>
            <h1>Vehicles</h1>
            <VehiclesList />
        </div>
        </>
    );
};

export default Vehicles;
